import { Bot, Building2, CheckCircle2, FilePenLine, Flame, ShieldCheck, Sparkles, UsersRound, XCircle } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { QuickCreate, fieldClass, labelClass, submitClass } from "@/components/quick-create";
import { StatusBadge } from "@/components/status-badge";
import { getCurrentActor } from "@/lib/current-actor";
import { aiAssistOutputSchema } from "@/modules/ai/domain";
import { listAiWorkspace } from "@/modules/ai/service";
import { can } from "@/modules/shared/tenant";
import { createAiAssistAction, reviewAiAssistAction } from "./actions";

export const metadata = { title: "Assistente IA" };
const card = "rounded-2xl border border-slate-200 bg-white p-5 shadow-sm";
const smallButton = "flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 text-[11px] font-bold text-slate-700 transition hover:border-amber-300 hover:bg-amber-50";

export default async function AssistantPage() {
  const actor = await getCurrentActor();
  const workspace = await listAiWorkspace(actor);
  const generated = workspace.requests.filter((item) => item.status === "GENERATED").length;
  return <div className="space-y-7">
    <PageHeader eyebrow="IA assistiva com governança" title="Assistente comercial" description="Resumos, classificações e rascunhos usam somente dados autorizados da organização. Toda saída exige revisão humana e nunca é enviada automaticamente." action={<div className="flex flex-wrap gap-2"><QuickCreate label="Resumir cliente"><form action={createAiAssistAction} className="grid gap-3"><input name="kind" type="hidden" value="CUSTOMER_SUMMARY" /><label className={labelClass}>Cliente *<select className={fieldClass} name="entityId" required><option value="">Selecione</option>{workspace.companies.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className={submitClass}>Gerar rascunho</button></form></QuickCreate><QuickCreate label="Classificar lead"><form action={createAiAssistAction} className="grid gap-3"><input name="kind" type="hidden" value="LEAD_CLASSIFICATION" /><label className={labelClass}>Lead *<select className={fieldClass} name="entityId" required><option value="">Selecione</option>{workspace.leads.map((item) => <option key={item.id} value={item.id}>{item.title} · {item.company.name}</option>)}</select></label><button className={submitClass}>Gerar classificação</button></form></QuickCreate><QuickCreate label="Criar rascunho"><form action={createAiAssistAction} className="grid gap-3"><input name="kind" type="hidden" value="MESSAGE_DRAFT" /><label className={labelClass}>Empresa *<select className={fieldClass} name="entityId" required><option value="">Selecione</option>{workspace.companies.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className={submitClass}>Gerar mensagem</button></form></QuickCreate></div>} />
    <section className="grid gap-4 sm:grid-cols-3"><div className={card}><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><ShieldCheck size={21} /></span><div><p className="text-xs text-slate-500">Provedor ativo</p><strong className="text-sm">{workspace.configuration.provider}</strong></div></div><p className="mt-3 text-[11px] text-slate-400">Modelo {workspace.configuration.model}; chave apenas no servidor.</p></div><div className={card}><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-amber-50 text-amber-700"><Sparkles size={21} /></span><div><p className="text-xs text-slate-500">Aguardando revisão</p><strong className="text-2xl">{generated}</strong></div></div></div><div className={card}><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-blue-50 text-blue-700"><Bot size={21} /></span><div><p className="text-xs text-slate-500">Histórico auditável</p><strong className="text-2xl">{workspace.requests.length}</strong></div></div></div></section>
    <section className="grid gap-5 lg:grid-cols-2">{workspace.requests.length ? workspace.requests.map((request) => {
      const parsed = aiAssistOutputSchema.safeParse(request.output);
      const output = parsed.success ? parsed.data : null;
      const Icon = request.kind === "CUSTOMER_SUMMARY" ? Building2 : request.kind === "LEAD_CLASSIFICATION" ? Flame : FilePenLine;
      return <article className={card} key={request.id}><header className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-slate-950 text-amber-400"><Icon size={18} /></span><div className="min-w-0 flex-1"><p className="text-sm font-bold">{output?.title ?? request.kind}</p><p className="mt-1 text-[11px] text-slate-500">{request.provider} · {request.model} · {request.createdAt.toLocaleString("pt-BR")}</p></div><StatusBadge>{request.status}</StatusBadge></header>{request.error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-xs text-red-700">{request.error}</p>}{output && <div className="mt-4 space-y-4"><p className="text-sm leading-6 text-slate-700">{output.summary}</p>{output.classification && <div className="flex items-center gap-2"><StatusBadge>{output.classification}</StatusBadge><span className="text-xs text-slate-500">Confiança: {output.confidence}%</span></div>}{output.highlights.length > 0 && <div><p className="text-[11px] font-black uppercase tracking-wider text-slate-400">Destaques</p><ul className="mt-2 space-y-1 text-xs text-slate-600">{output.highlights.map((item) => <li key={item}>• {item}</li>)}</ul></div>}{output.risks.length > 0 && <div className="rounded-xl bg-orange-50 p-3"><p className="text-[11px] font-black uppercase tracking-wider text-orange-700">Riscos</p><ul className="mt-2 space-y-1 text-xs text-orange-900">{output.risks.map((item) => <li key={item}>• {item}</li>)}</ul></div>}{output.draftBody && <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-bold">{output.draftSubject}</p><p className="mt-3 whitespace-pre-wrap text-xs leading-6 text-slate-700">{output.draftBody}</p></div>}<div className="rounded-xl bg-emerald-50 p-3 text-xs text-emerald-900"><strong>Próximo passo sugerido:</strong> {output.suggestedNextStep}</div>{request.status === "GENERATED" && can(actor.role, "ai:review") && <form action={reviewAiAssistAction} className="flex flex-wrap gap-2"><input name="requestId" type="hidden" value={request.id} /><button className={smallButton} name="decision" value="APPROVE"><CheckCircle2 size={13} />Aprovar rascunho</button><button className={smallButton} name="decision" value="REJECT"><XCircle size={13} />Rejeitar</button></form>}<p className="text-[10px] leading-4 text-slate-400">Contexto minimizado · digest {request.inputDigest.slice(0, 12)}… · aprovar não envia a mensagem</p></div>}</article>;
    }) : <div className={`${card} col-span-full py-12 text-center`}><UsersRound className="mx-auto text-slate-300" size={40} /><h2 className="mt-4 font-bold">Nenhum rascunho gerado</h2><p className="mt-2 text-sm text-slate-500">Escolha um cliente ou lead para iniciar a assistência.</p></div>}</section>
  </div>;
}
