import { CalendarDays, CircleUserRound, MoreHorizontal, Plus } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { getCurrentActor } from "@/lib/current-actor";
import { pipelineView } from "@/lib/view-data";
import { formatCurrency } from "@/lib/utils";

export const metadata = { title: "Funil comercial" };

export default async function PipelinePage() {
  const stages = await pipelineView(await getCurrentActor());
  const total = stages.flatMap((stage) => stage.opportunities).reduce((sum, item) => sum + item.value, 0);
  return <div className="space-y-6"><PageHeader eyebrow="Funil e produtividade" title="Pipeline principal" description={`${stages.reduce((sum, stage) => sum + stage.opportunities.length, 0)} oportunidades abertas somando ${formatCurrency(total)}.`} action={<button className="flex items-center gap-2 rounded-xl bg-amber-500 px-4 py-2.5 text-sm font-bold text-slate-950 hover:bg-amber-400"><Plus size={17} /> Nova oportunidade</button>} />
    <div className="flex flex-wrap items-center gap-2"><button className="rounded-xl bg-slate-950 px-4 py-2 text-xs font-bold text-white">Pipeline principal</button><button className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs font-semibold text-slate-600">Minha equipe</button><button className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs font-semibold text-slate-600">Fechamento este mês</button></div>
    <section aria-label="Quadro Kanban de oportunidades" className="grid items-start gap-4 overflow-x-auto pb-4 md:grid-cols-2 xl:grid-cols-4">{stages.map((stage) => { const value = stage.opportunities.reduce((sum, item) => sum + item.value, 0); return <div key={stage.id} className="min-w-[280px] rounded-2xl bg-slate-100/80 p-3"><div className="flex items-center justify-between px-1 pb-3"><div className="flex items-center gap-2"><span className="size-2.5 rounded-full" style={{ backgroundColor: stage.color }} /><h2 className="text-xs font-bold uppercase tracking-wider text-slate-700">{stage.name}</h2><span className="rounded-full bg-white px-2 py-0.5 text-[10px] font-bold text-slate-500">{stage.opportunities.length}</span></div><span className="text-[11px] font-semibold text-slate-500">{formatCurrency(value)}</span></div><div className="space-y-3">{stage.opportunities.map((opportunity) => <article key={opportunity.id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium text-slate-500">{opportunity.company}</p><h3 className="mt-1 text-sm font-bold leading-5 text-slate-900">{opportunity.title}</h3></div><button aria-label="Mais ações" className="text-slate-400"><MoreHorizontal size={17} /></button></div><p className="mt-4 text-lg font-bold tracking-tight text-slate-950">{formatCurrency(opportunity.value)}</p><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 text-[11px] text-slate-500"><span className="flex items-center gap-1"><CircleUserRound size={14} />{opportunity.owner}</span><span className="flex items-center gap-1"><CalendarDays size={14} />{opportunity.due}</span></div><div className="mt-3 grid grid-cols-2 gap-2"><button className="rounded-lg border border-slate-200 py-2 text-[11px] font-bold text-slate-600 hover:bg-slate-50">Voltar</button><button className="rounded-lg bg-slate-950 py-2 text-[11px] font-bold text-white hover:bg-amber-500 hover:text-slate-950">Avançar</button></div></article>)}</div></div>; })}</section>
    <p className="text-xs text-slate-500">No celular, as colunas podem ser percorridas horizontalmente e cada oportunidade oferece ações explícitas para avançar ou voltar de etapa.</p>
  </div>;
}
