import { Bot, Braces, CheckCircle2, Clock3, FileInput, History, MailCheck, ShieldCheck, Webhook, Workflow } from "lucide-react";
import { MetricCard } from "@/components/metric-card";
import { PageHeader } from "@/components/page-header";
import { QuickCreate, fieldClass, labelClass, submitClass } from "@/components/quick-create";
import { StatusBadge } from "@/components/status-badge";
import { getCurrentActor } from "@/lib/current-actor";
import { listAutomationWorkspace } from "@/modules/automations/service";
import { listIntegrationWorkspace } from "@/modules/integrations/service";
import { can } from "@/modules/shared/tenant";
import { createAutomationPresetAction, createCaptureFormAction, createSandboxConnectionAction, createTemplateAction, publishAutomationAction, retryAutomationAction, reviewOutboundAction, reviewTemplateAction } from "./actions";
import { WebhookCreateForm } from "./webhook-create-form";

export const metadata = { title: "Automações e integrações" };
const card = "rounded-2xl border border-slate-200 bg-white p-5 shadow-sm";
const smallButton = "rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 text-[11px] font-bold text-slate-700 transition hover:border-amber-300 hover:bg-amber-50";

export default async function AutomationsPage() {
  const actor = await getCurrentActor();
  const [{ automations, runs }, integrations] = await Promise.all([listAutomationWorkspace(actor), listIntegrationWorkspace(actor)]);
  const canWrite = can(actor.role, "automation:write");
  const pendingApprovals = integrations.approvals.filter((item) => item.status === "PENDING").length;
  const failedRuns = runs.filter((run) => run.status === "FAILED").length;
  return <div className="space-y-7">
    <PageHeader eyebrow="Orquestração segura" title="Automações e integrações" description="Gatilhos versionados, fila durável, tentativas controladas e aprovação humana antes de qualquer ação externa." action={canWrite ? <QuickCreate label="Nova automação"><form action={createAutomationPresetAction} className="grid gap-3"><label className={labelClass}>Nome *<input className={fieldClass} name="name" required /></label><label className={labelClass}>Descrição<textarea className={`${fieldClass} h-20 py-3`} name="description" /></label><label className={labelClass}>Gatilho<select className={fieldClass} name="triggerType"><option value="LEAD_CREATED">Lead criado</option><option value="CAPTURE_FORM_SUBMITTED">Formulário recebido</option><option value="WEBHOOK_RECEIVED">Webhook recebido</option><option value="RENEWAL_DUE">Renovação próxima</option></select></label><div className="grid grid-cols-2 gap-3"><label className={labelClass}>Campo condicional<input className={fieldClass} name="conditionField" placeholder="lead.source" /></label><label className={labelClass}>Valor esperado<input className={fieldClass} name="conditionValue" /></label></div><label className={labelClass}>Ação<select className={fieldClass} name="actionType"><option value="CREATE_TASK">Criar tarefa</option><option value="CREATE_NOTIFICATION">Criar notificação</option></select></label><label className={labelClass}>Título da ação *<input className={fieldClass} name="actionTitle" required /></label><label className={labelClass}>Prazo da tarefa (horas)<input className={fieldClass} defaultValue="24" min="0" name="dueInHours" type="number" /></label><button className={submitClass}>Salvar rascunho v1</button></form></QuickCreate> : null} />

    <section aria-label="Indicadores de automação" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Publicadas" value={String(automations.filter((item) => item.status === "PUBLISHED").length)} detail="Versões ativas" icon={Workflow} accent /><MetricCard label="Execuções" value={String(runs.length)} detail={`${failedRuns} com falha`} icon={History} /><MetricCard label="Aprovações pendentes" value={String(pendingApprovals)} detail="Nenhum envio automático" icon={ShieldCheck} /><MetricCard label="Conectores" value={String(integrations.connections.length)} detail="E-mail, agenda, WhatsApp e webhook" icon={Webhook} /></section>

    <section className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
      <div className={card}><div className="flex items-center gap-2"><Workflow className="text-amber-600" size={18} /><h2 className="font-bold">Automações versionadas</h2></div><div className="mt-4 space-y-3">{automations.length ? automations.map((automation) => <article className="rounded-xl border border-slate-100 bg-slate-50 p-4" key={automation.id}><div className="flex flex-wrap items-start gap-3"><div className="min-w-0 flex-1"><p className="text-sm font-bold">{automation.name}</p><p className="mt-1 text-xs text-slate-500">{automation.triggerType} · versão {automation.currentVersion}</p></div><StatusBadge>{automation.status}</StatusBadge>{automation.status === "DRAFT" && can(actor.role, "automation:publish") && <form action={publishAutomationAction}><input name="automationId" type="hidden" value={automation.id} /><button className={smallButton}>Publicar</button></form>}</div>{automation.description && <p className="mt-3 text-xs leading-5 text-slate-600">{automation.description}</p>}</article>) : <p className="text-sm text-slate-500">Nenhuma automação criada.</p>}</div></div>
      <div className={card}><div className="flex items-center gap-2"><History className="text-amber-600" size={18} /><h2 className="font-bold">Fila e auditoria</h2></div><div className="mt-4 space-y-3">{runs.length ? runs.slice(0, 10).map((run) => <article className="rounded-xl bg-slate-50 p-3" key={run.id}><div className="flex items-center gap-2"><p className="min-w-0 flex-1 truncate text-xs font-bold">{run.automation.name}</p><StatusBadge>{run.status}</StatusBadge></div><p className="mt-2 text-[11px] text-slate-500">Tentativa {run.attempt}/{run.maxAttempts} · {run.actionLogs.length} ação(ões)</p>{run.error && <p className="mt-2 text-[11px] text-red-700">{run.error}</p>}{run.status === "FAILED" && run.attempt < run.maxAttempts && canWrite && <form action={retryAutomationAction} className="mt-2"><input name="runId" type="hidden" value={run.id} /><button className={smallButton}>Tentar novamente</button></form>}</article>) : <p className="text-sm text-slate-500">A fila está vazia.</p>}</div></div>
    </section>

    <section className="grid gap-5 lg:grid-cols-2 xl:grid-cols-4">
      <div className={card}><div className="flex items-center gap-2"><MailCheck className="text-blue-600" size={18} /><h2 className="font-bold">Adaptadores</h2></div><div className="mt-4 space-y-2">{integrations.connections.map((connection) => <div className="flex items-center justify-between rounded-xl bg-slate-50 p-3" key={connection.id}><div><p className="text-xs font-bold">{connection.name}</p><p className="text-[11px] text-slate-500">{connection.provider}</p></div><StatusBadge>{connection.status}</StatusBadge></div>)}</div>{can(actor.role, "integration:write") && <form action={createSandboxConnectionAction} className="mt-4 grid gap-2"><input className={fieldClass} name="name" placeholder="Nome do conector" required /><select className={fieldClass} name="provider"><option value="EMAIL">E-mail</option><option value="CALENDAR">Calendário</option><option value="WHATSAPP">WhatsApp oficial</option><option value="WEBHOOK">Webhook</option></select><button className={submitClass}>Ativar sandbox</button></form>}</div>
      <div className={card}><div className="flex items-center gap-2"><Braces className="text-violet-600" size={18} /><h2 className="font-bold">Webhook autenticado</h2></div><p className="mt-3 text-xs leading-5 text-slate-500">Bearer token, limite de 256 KB e Idempotency-Key obrigatória.</p>{can(actor.role, "integration:write") && <div className="mt-4"><WebhookCreateForm /></div>}{integrations.endpoints.map((endpoint) => <div className="mt-3 rounded-xl bg-slate-50 p-3" key={endpoint.id}><p className="text-xs font-bold">{endpoint.name}</p><code className="mt-1 block break-all text-[10px] text-slate-500">/api/webhooks/{endpoint.publicId}</code><p className="mt-1 text-[10px] text-slate-400">Token final …{endpoint.secretHint} · {endpoint.deliveries.length} entrega(s) recente(s)</p></div>)}</div>
      <div className={card}><div className="flex items-center gap-2"><FileInput className="text-emerald-600" size={18} /><h2 className="font-bold">Formulários públicos</h2></div>{integrations.forms.map((form) => <div className="mt-3 rounded-xl bg-slate-50 p-3" key={form.id}><p className="text-xs font-bold">{form.name}</p><a className="mt-1 block break-all text-[10px] font-semibold text-blue-700 hover:underline" href={`/captura/${form.publicId}`}>/captura/{form.publicId}</a><p className="mt-1 text-[10px] text-slate-400">{form.submissions.length} envio(s) recente(s)</p></div>)}{can(actor.role, "integration:write") && <form action={createCaptureFormAction} className="mt-4 grid gap-2"><input className={fieldClass} name="name" placeholder="Nome do formulário" required /><input className={fieldClass} name="description" placeholder="Descrição" /><input className={fieldClass} name="source" placeholder="Origem" /><button className={submitClass}>Criar formulário</button></form>}</div>
      <div className={card}><div className="flex items-center gap-2"><Bot className="text-rose-600" size={18} /><h2 className="font-bold">Templates e aprovações</h2></div>{integrations.approvals.slice(0, 5).map((approval) => <div className="mt-3 rounded-xl bg-slate-50 p-3" key={approval.id}><div className="flex items-center gap-2"><p className="min-w-0 flex-1 text-xs font-bold">{approval.provider} · {approval.recipient}</p><StatusBadge>{approval.status}</StatusBadge></div>{approval.status === "PENDING" && can(actor.role, "integration:approve") && <form action={reviewOutboundAction} className="mt-2 flex gap-2"><input name="approvalId" type="hidden" value={approval.id} /><button className={smallButton} name="decision" value="APPROVE">Aprovar sandbox</button><button className={smallButton} name="decision" value="REJECT">Rejeitar</button></form>}</div>)}{can(actor.role, "integration:write") && <details className="mt-4"><summary className="cursor-pointer text-xs font-bold text-amber-700">Novo template</summary><form action={createTemplateAction} className="mt-3 grid gap-2"><input className={fieldClass} name="name" placeholder="Nome" required /><select className={fieldClass} name="provider"><option value="EMAIL">E-mail</option><option value="WHATSAPP">WhatsApp</option></select><input className={fieldClass} name="subject" placeholder="Assunto" /><textarea className={`${fieldClass} h-20 py-3`} name="body" placeholder="Conteúdo" required /><button className={submitClass}>Enviar para aprovação</button></form></details>}{integrations.templates.filter((template) => template.status === "PENDING").map((template) => <form action={reviewTemplateAction} className="mt-2 flex items-center gap-2 rounded-xl border border-amber-100 p-2" key={template.id}><input name="templateId" type="hidden" value={template.id} /><span className="min-w-0 flex-1 truncate text-[11px]">{template.name}</span><button className={smallButton} name="decision" value="APPROVE"><CheckCircle2 size={12} /></button><button className={smallButton} name="decision" value="REJECT">Rejeitar</button></form>)}</div>
    </section>

    <section className="flex items-start gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-xs leading-5 text-emerald-900"><Clock3 className="mt-0.5 shrink-0" size={17} /><p><strong>Garantia antirrepetição:</strong> o evento é único por automação e cada ação tem uma chave própria. Retentativas reutilizam os logs concluídos e saídas externas ficam em aprovação.</p></section>
  </div>;
}
