import { ChartNoAxesCombined, CircleDollarSign, Download, Gauge, ListChecks, Target, TrendingUp, UsersRound } from "lucide-react";
import { MetricCard } from "@/components/metric-card";
import { PageHeader } from "@/components/page-header";
import { getCurrentActor } from "@/lib/current-actor";
import { formatCurrency } from "@/lib/utils";
import { getCrmReport } from "@/modules/reports/service";
import { can } from "@/modules/shared/tenant";
import { exportReportAction } from "./actions";

export const metadata = { title: "Relatórios gerenciais" };
const card = "rounded-2xl border border-slate-200 bg-white p-5 shadow-sm";

function Progress({ value, max, color = "bg-amber-500" }: { value: number; max: number; color?: string }) {
  return <div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${color}`} style={{ width: `${max ? Math.max(3, value / max * 100) : 0}%` }} /></div>;
}

export default async function ReportsPage() {
  const actor = await getCurrentActor();
  const report = await getCrmReport(actor);
  const maxOrigin = Math.max(1, ...report.origins.map((item) => item.total));
  const maxSegmentMrr = Math.max(1, ...report.segments.map((item) => item.mrr));
  return <div className="space-y-7">
    <PageHeader eyebrow="Gestão e previsibilidade" title="Relatórios conciliáveis" description="Os indicadores são calculados diretamente dos registros detalhados da organização ativa, com exportação individual e auditada." action={can(actor.role, "reports:export") ? <form action={exportReportAction} className="flex gap-2"><select className="rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold" name="reportType"><option value="EXECUTIVO">Executivo</option><option value="VENDEDORES">Vendedores</option><option value="SEGMENTOS">Segmentos</option></select><button className="flex items-center gap-2 rounded-xl bg-amber-500 px-4 py-2.5 text-sm font-bold text-slate-950"><Download size={16} />Exportar CSV</button></form> : null} />
    <section aria-label="Indicadores executivos" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Pipeline aberto" value={formatCurrency(report.executive.pipelineValue)} detail={`${formatCurrency(report.executive.weightedForecast)} ponderado`} icon={Target} accent /><MetricCard label="Conversão de ganhos" value={`${report.executive.winRate}%`} detail={`${report.executive.wins} ganhos · ${report.executive.losses} perdas`} icon={TrendingUp} /><MetricCard label="MRR ativo" value={formatCurrency(report.executive.mrr)} detail={`${formatCurrency(report.executive.projectRevenue)} em projetos`} icon={CircleDollarSign} /><MetricCard label="Upsell potencial" value={formatCurrency(report.executive.openUpsellPotential)} detail={`${formatCurrency(report.executive.bookedUpsell)} realizado`} icon={Gauge} /></section>
    <section className="grid gap-5 xl:grid-cols-3">
      <article className={card}><div className="flex items-center gap-2"><UsersRound className="text-blue-600" size={18} /><h2 className="font-bold">Origem e qualificação</h2></div><p className="mt-2 text-xs text-slate-500">{report.executive.qualifiedLeads}/{report.executive.leads} leads qualificados ({report.executive.leadQualificationRate}%).</p><div className="mt-5 space-y-4">{report.origins.map((origin) => <div key={origin.name}><div className="mb-2 flex justify-between text-xs"><span className="font-semibold">{origin.name}</span><span className="text-slate-500">{origin.qualified}/{origin.total}</span></div><Progress max={maxOrigin} value={origin.total} color="bg-blue-500" /></div>)}</div></article>
      <article className={card}><div className="flex items-center gap-2"><ListChecks className="text-red-600" size={18} /><h2 className="font-bold">SLA e perdas</h2></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-red-50 p-3"><p className="text-[11px] text-red-700">Atividades vencidas</p><strong className="mt-1 block text-xl text-red-950">{report.executive.sla.overdueActivities}/{report.executive.sla.openActivities}</strong></div><div className="rounded-xl bg-orange-50 p-3"><p className="text-[11px] text-orange-700">Tickets vencidos</p><strong className="mt-1 block text-xl text-orange-950">{report.executive.sla.overdueTickets}/{report.executive.sla.openTickets}</strong></div></div><div className="mt-4 space-y-2">{report.losses.length ? report.losses.map((loss) => <div className="flex items-center gap-3 rounded-xl bg-slate-50 p-3" key={loss.reason}><span className="min-w-0 flex-1 text-xs font-semibold">{loss.reason}</span><span className="text-[11px] text-slate-500">{loss.total} · {formatCurrency(loss.value)}</span></div>) : <p className="text-sm text-slate-500">Nenhuma perda registrada.</p>}</div></article>
      <article className={card}><div className="flex items-center gap-2"><ChartNoAxesCombined className="text-violet-600" size={18} /><h2 className="font-bold">Segmentos</h2></div><div className="mt-5 space-y-4">{report.segments.map((segment) => <div key={segment.name}><div className="mb-2 flex items-end justify-between gap-3"><div><p className="text-xs font-semibold">{segment.name}</p><p className="text-[11px] text-slate-500">{segment.customers}/{segment.companies} clientes</p></div><strong className="text-xs">{formatCurrency(segment.mrr)} MRR</strong></div><Progress max={maxSegmentMrr} value={segment.mrr} color="bg-violet-500" /></div>)}</div></article>
    </section>
    <section className={card}><div className="flex items-center gap-2"><TrendingUp className="text-emerald-600" size={18} /><h2 className="font-bold">Desempenho por vendedor</h2></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead><tr className="border-b border-slate-200 text-slate-400"><th className="pb-3">Vendedor</th><th className="pb-3">Abertas</th><th className="pb-3">Ganhas</th><th className="pb-3">Perdidas</th><th className="pb-3">Pipeline</th><th className="pb-3">Receita ganha</th></tr></thead><tbody>{report.sellers.map((seller) => <tr className="border-b border-slate-100" key={seller.ownerId}><td className="py-3 font-semibold">{seller.name}</td><td>{seller.open}</td><td>{seller.won}</td><td>{seller.lost}</td><td>{formatCurrency(seller.openValue)}</td><td>{formatCurrency(seller.wonValue)}</td></tr>)}</tbody></table></div></section>
    <p className="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-xs leading-5 text-slate-600"><strong>Conciliação:</strong> {report.reconciliation.opportunityIds.length} oportunidades, {report.reconciliation.mrrRevenueIds.length} receitas MRR, {report.reconciliation.projectRevenueIds.length} receitas de projetos e {report.reconciliation.upsellIds.length} upsells abertos compõem este painel.</p>
  </div>;
}
