import { FileCheck2, FileClock, Send } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { QuickCreate, fieldClass, labelClass, submitClass } from "@/components/quick-create";
import { StatusBadge } from "@/components/status-badge";
import { getCurrentActor } from "@/lib/current-actor";
import { companiesView, pipelineView, proposalsView } from "@/lib/view-data";
import { formatCurrency } from "@/lib/utils";
import { createProposalAction } from "../actions";

export const metadata = { title: "Propostas" };

export default async function ProposalsPage() {
  const actor = await getCurrentActor(); const [proposals, companies, stages] = await Promise.all([proposalsView(actor), companiesView(actor), pipelineView(actor)]); const opportunities = stages.flatMap((stage) => stage.opportunities);
  return <div className="space-y-6"><PageHeader eyebrow="Comercial e receita" title="Propostas comerciais" description="Versionamento, aprovação humana e rastreabilidade antes de qualquer envio externo." action={<QuickCreate label="Nova proposta"><form action={createProposalAction} className="grid gap-3"><label className={labelClass}>Empresa *<select className={fieldClass} name="companyId" required><option value="">Selecione</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select></label><label className={labelClass}>Oportunidade *<select className={fieldClass} name="opportunityId" required><option value="">Selecione</option>{opportunities.map((item) => <option key={item.id} value={item.id}>{item.company} — {item.title}</option>)}</select></label><label className={labelClass}>Título *<input className={fieldClass} name="title" required /></label><label className={labelClass}>Item *<input className={fieldClass} name="description" required /></label><div className="grid grid-cols-2 gap-3"><label className={labelClass}>Quantidade<input className={fieldClass} name="quantity" type="number" min="1" defaultValue="1" /></label><label className={labelClass}>Preço unitário<input className={fieldClass} name="unitPrice" type="number" min="0" step="0.01" required /></label></div><button className={submitClass}>Criar rascunho</button></form></QuickCreate>} />
    <section className="grid gap-4 sm:grid-cols-3"><article className="rounded-2xl border border-slate-200 bg-white p-5"><FileClock className="text-amber-500" /><p className="mt-4 text-2xl font-bold">2</p><p className="text-sm text-slate-500">Aguardando aprovação</p></article><article className="rounded-2xl border border-slate-200 bg-white p-5"><Send className="text-blue-500" /><p className="mt-4 text-2xl font-bold">R$ 86,5 mil</p><p className="text-sm text-slate-500">Em negociação</p></article><article className="rounded-2xl bg-slate-950 p-5 text-white"><FileCheck2 className="text-emerald-400" /><p className="mt-4 text-2xl font-bold">41%</p><p className="text-sm text-slate-400">Taxa de aceite no mês</p></article></section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-slate-50 text-[11px] uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Proposta</th><th className="px-5 py-3">Empresa</th><th className="px-5 py-3">Validade</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Total</th></tr></thead><tbody className="divide-y divide-slate-100">{proposals.map((proposal) => <tr key={proposal.id}><td className="px-5 py-4"><span className="text-xs font-bold text-amber-700">{proposal.number}</span><strong className="ml-3 text-sm text-slate-900">{proposal.title}</strong></td><td className="px-5 py-4 text-sm text-slate-600">{proposal.company}</td><td className="px-5 py-4 text-sm text-slate-500">{proposal.validUntil}</td><td className="px-5 py-4"><StatusBadge>{proposal.status}</StatusBadge></td><td className="px-5 py-4 text-right text-sm font-bold text-slate-900">{formatCurrency(proposal.total)}</td></tr>)}</tbody></table></div></section>
  </div>;
}
